# Generated by Django 3.0.3 on 2020-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_manager', '0002_auto_20200410_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='memobox',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='word',
            name='foreign_example',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='native_example',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='native_word_other',
            field=models.TextField(blank=True, default=''),
        ),
    ]
